//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GachaAnalyzer.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GachaAnalyzer.Language.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 🔮 分析运气 的本地化字符串。
        /// </summary>
        internal static string ButtonCalc {
            get {
                return ResourceManager.GetString("ButtonCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用了井（扣除一个保底3星） 的本地化字符串。
        /// </summary>
        internal static string CheckPity {
            get {
                return ResourceManager.GetString("CheckPity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FES庆典池 (6%) 的本地化字符串。
        /// </summary>
        internal static string ComboFES {
            get {
                return ResourceManager.GetString("ComboFES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规池 (3%) 的本地化字符串。
        /// </summary>
        internal static string ComboNormal {
            get {
                return ResourceManager.GetString("ComboNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick Up池（0.7%） 的本地化字符串。
        /// </summary>
        internal static string ComboPickup {
            get {
                return ResourceManager.GetString("ComboPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的出彩数 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidC3 {
            get {
                return ResourceManager.GetString("ErrorInvalidC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的总抽数 的本地化字符串。
        /// </summary>
        internal static string ErrorInvalidPulls {
            get {
                return ResourceManager.GetString("ErrorInvalidPulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果井了，出彩数至少为1（含井） 的本地化字符串。
        /// </summary>
        internal static string ErrorPityWithZero {
            get {
                return ResourceManager.GetString("ErrorPityWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析卡池概率 的本地化字符串。
        /// </summary>
        internal static string ErrorPoolParse {
            get {
                return ResourceManager.GetString("ErrorPoolParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个带概率的卡池或联系开发者 的本地化字符串。
        /// </summary>
        internal static string ErrorPoolSelect {
            get {
                return ResourceManager.GetString("ErrorPoolSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95% 区间: [{0:F2}, {1:F2}] 的本地化字符串。
        /// </summary>
        internal static string FormatCI {
            get {
                return ResourceManager.GetString("FormatCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评级: {0} 的本地化字符串。
        /// </summary>
        internal static string FormatGrade {
            get {
                return ResourceManager.GetString("FormatGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过: {0:F1}% 的sensei 的本地化字符串。
        /// </summary>
        internal static string FormatPercentile {
            get {
                return ResourceManager.GetString("FormatPercentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显著性: {0} 的本地化字符串。
        /// </summary>
        internal static string FormatSignificance {
            get {
                return ResourceManager.GetString("FormatSignificance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z值: {0:F3} 的本地化字符串。
        /// </summary>
        internal static string FormatZ {
            get {
                return ResourceManager.GetString("FormatZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蔚蓝档案 · 抽卡概率分析器 的本地化字符串。
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📊 分析结果 的本地化字符串。
        /// </summary>
        internal static string GroupResult {
            get {
                return ResourceManager.GetString("GroupResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出彩数（3星）： 的本地化字符串。
        /// </summary>
        internal static string LabelC3 {
            get {
                return ResourceManager.GetString("LabelC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 95% 区间: 的本地化字符串。
        /// </summary>
        internal static string LabelCI {
            get {
                return ResourceManager.GetString("LabelCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评级: 的本地化字符串。
        /// </summary>
        internal static string LabelGrade {
            get {
                return ResourceManager.GetString("LabelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过: 的本地化字符串。
        /// </summary>
        internal static string LabelPercentile {
            get {
                return ResourceManager.GetString("LabelPercentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡池: 的本地化字符串。
        /// </summary>
        internal static string LabelPool {
            get {
                return ResourceManager.GetString("LabelPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总抽数: 的本地化字符串。
        /// </summary>
        internal static string LabelPulls {
            get {
                return ResourceManager.GetString("LabelPulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显著性: 的本地化字符串。
        /// </summary>
        internal static string LabelSignificance {
            get {
                return ResourceManager.GetString("LabelSignificance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z值: 的本地化字符串。
        /// </summary>
        internal static string LabelZ {
            get {
                return ResourceManager.GetString("LabelZ", resourceCulture);
            }
        }
    }
}
